config_version: simclr_finegrain_v3.1.run6
front_end: 'simclr'
path: 'r50_1x_sk0/saved_model/'
w2_depth: 2
lr: 0.00003
patience: 5
batch_size: 128   # use 64 when experience bottleneck
epochs: 500
generator_seed: 42
validation_split: 0.1
generator_type: simclr_finegrain
kernel_initializer: glorot_normal
kernel_seed: 42
headless: True
mixed_precision: True


# Use tfrecords and headless
# batch_size = 128
# Add .repeat(NUM_EPOCHS)
# Use mixed_precision: https://www.tensorflow.org/guide/mixed_precision
