config_version: vgg16_finegrain_v2.1.run1
front_end: 'vgg16'
path: 
w2_depth: 2
lr: 0.00003
patience: 5
batch_size: 128
epochs: 500
generator_seed: 42
validation_split: 0.1
generator_type: vgg16_finegrain

layer: flatten


# This is in fact the original converted to this format.
# with the difference being now we re-train 2 FCs from scratch.