config_version: vgg16_finegrain_v1.1.run1
front_end: 'vgg16'
path: 
w2_depth: 2
lr: 0.00003
patience: 5
batch_size: 128
epochs: 500
generator_seed: 42
validation_split: 0.1
generator_type: vgg16_finegrain

layer: fc2


# This is in fact the original converted to this format.
# added layer to be consistent with v2 where we re-train the old (fc1 & fc2) from scratch.